# Creating & Uploading Dataset
## Experiment - 10

### Gunjan Goyal
### 25070123048
### E&TC-A3

In [ ]:
# Upload the Dataset
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Cars93.csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.size

930

In [ ]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [ ]:
import pandas as pd
data = {
    "Roll_No": [101,102,103,104,105],
    "Gender": ["Feamle", "Male", "Female","Male","Male"],
    "Department": ["E&TC","CSE","ME","CE","AIML"],
    "CGPA": [ 8.9, 7.8,9.12,8.11,7.95]
}
df = pd.DataFrame(data)
df.to_csv("Student.csv", index=False)
df

   Roll_No  Gender Department  CGPA
0      101  Feamle       E&TC  8.90
1      102    Male        CSE  7.80
2      103  Female         ME  9.12
3      104    Male         CE  8.11
4      105    Male       AIML  7.95

In [ ]:
df.size

20

In [ ]:
df.shape

(5, 4)

In [ ]:
df.info

<bound method DataFrame.info of    Roll_No  Gender Department  CGPA
0      101  Feamle       E&TC  8.90
1      102    Male        CSE  7.80
2      103  Female         ME  9.12
3      104    Male         CE  8.11
4      105    Male       AIML  7.95>

In [ ]:
# Access Information of Column Departent
df['Department']

0    E&TC
1     CSE
2      ME
3      CE
4    AIML
Name: Department, dtype: object

In [ ]:
# Access Information of PRN 103
df.loc[2]

Roll_No          103
Gender        Female
Department        ME
CGPA            9.12
Name: 2, dtype: object

In [ ]:
# Find out Data type of Each Column
df.dtypes

Roll_No         int64
Gender         object
Department     object
CGPA          float64
dtype: object

In [ ]:
# Calculate Mean, Meadian, Mode
df["CGPA"].mean()

In [ ]:
df["CGPA"].median()

8.11

In [ ]:
df["CGPA"].mode()

0    7.80
1    7.95
2    8.11
3    8.90
4    9.12
Name: CGPA, dtype: float64

In [ ]:
# Delete Gender Column
df.drop("Gender",axis=1)

   Roll_No Department  CGPA
0      101       E&TC  8.90
1      102        CSE  7.80
2      103         ME  9.12
3      104         CE  8.11
4      105       AIML  7.95

In [ ]:
# CGPA of Topper
df["CGPA"].max()

9.12

In [ ]:
# CGPA of PRN 105
df["CGPA"].loc[4]

np.float64(7.95)