# Study_Pandas_library
## Experiment - 9

### Gunjan Goyal
### 25070123048
### E&TC-A3

In [1]:
import pandas as pd
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [5]:
# Create DataFrame
data={
    "Name":["A","B","C"],
    "Marks":[85,90,78]
}
df = pd.DataFrame(data)
df

  Name  Marks
0    A     85
1    B     90
2    C     78

In [ ]:
df.head() # Gives first 5 entries
df.tail() # Gives last 5 entries

In [6]:
df.shape

(3, 2)

In [8]:
df.ndim # Gives number of columns

2

In [9]:
df.size

6

In [10]:
# Display Column Names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [11]:
# Check Data Types of Each Column
df.dtypes

Name     object
Marks     int64
dtype: object

In [13]:
# Access Individual Column
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [15]:
df["Marks"]

0    85
1    90
2    78
Name: Marks, dtype: int64

In [16]:
df.loc[1]

Name      B
Marks    90
Name: 1, dtype: object

In [28]:
# Add New Column
''' If marks 80-90 First Class
If marks>=90 Distinction
If marks<80 Second Class'''
df["Grade"]=["First Class","Distinction","Second Class"]
df

  Name  Marks         Grade
0    A     85   First Class
1    B     90   Distinction
2    C     78  Second Class

In [29]:
# Update Data in Dataframe
''' Change Marks of Student A to 88'''
df.loc[0,"Marks"]=88
df

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    C     78  Second Class

In [30]:
# Delete a Column
df.drop("Grade",axis=1 ,inplace=True )
df

  Name  Marks
0    A     88
1    B     90
2    C     78

#### Perform Basic Statistical Analysis

In [36]:
Mean = df["Marks"].mean()
Mean

np.float64(85.33333333333333)

In [37]:
Mode = df["Marks"].mode()
Mode

0    78
1    88
2    90
Name: Marks, dtype: int64

In [38]:
Min = df["Marks"].min()
Min

78

In [39]:
Max = df["Marks"].max()
Max

90

#### Apply Conditional Filtering

In [40]:
''' Dislay Students Scoring More than 80'''
df[df["Marks"]>80]

  Name  Marks
0    A     88
1    B     90

In [45]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[15, np.nan, np.nan],"C3":[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

#### Conditional Statement

In [54]:
df1.isna()
# isna = is not a number

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [55]:
df1.notna()
# notna = not not a number

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [56]:
df1.isna().sum()
# sum - how many na values are there in each column

C1    1
C2    2
C3    0
dtype: int64

In [57]:
df1.dropna()
# NaN rows are dropped

     C1    C2  C3
0  11.0  15.0  10